version: "3.9"
services:
  postgres:
    image: postgres
    command: postgres -c 'max_connections=200'
    restart: always
    networks:
      - net
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "trading_chart"
      DATABASE_HOST: "0.0.0.0"

  grpc-server:
    build:
      dockerfile: grpc-server/Dockerfile
      context: .
    networks:
      - net
    environment:
      ENV: "development"
      GRPC_SERVER_PORT: "5051"
      DATABASE_DSN: "host=postgres user=postgres password=postgres dbname=trading_chart port=5432 sslmode=disable TimeZone=UTC"
    depends_on:
      - postgres

  websocket-listener:
    build:
      dockerfile: websocket-listener/Dockerfile
      context: .
    networks:
      - net
    environment:
      ENV: development
      GRPC_SERVER_URL: grpc-server:5051
      TRADE_SYMBOLS: btcusdt|ethusdt|pepeusdt
      BINANCE_WEBSOCKET_URL: wss://stream.binance.com:443
    depends_on:
      - grpc-server

networks:
  net:
    driver: bridge
