// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.9
// source: grpc-server/protobuf/trading_chart.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamOHLCCandlestickRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol     string  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OpenPrice  float64 `protobuf:"fixed64,2,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	HighPrice  float64 `protobuf:"fixed64,3,opt,name=high_price,json=highPrice,proto3" json:"high_price,omitempty"`
	LowPrice   float64 `protobuf:"fixed64,4,opt,name=low_price,json=lowPrice,proto3" json:"low_price,omitempty"`
	ClosePrice float64 `protobuf:"fixed64,5,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	StartTime  int64   `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
}

func (x *StreamOHLCCandlestickRequest) Reset() {
	*x = StreamOHLCCandlestickRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_server_protobuf_trading_chart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamOHLCCandlestickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOHLCCandlestickRequest) ProtoMessage() {}

func (x *StreamOHLCCandlestickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_protobuf_trading_chart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOHLCCandlestickRequest.ProtoReflect.Descriptor instead.
func (*StreamOHLCCandlestickRequest) Descriptor() ([]byte, []int) {
	return file_grpc_server_protobuf_trading_chart_proto_rawDescGZIP(), []int{0}
}

func (x *StreamOHLCCandlestickRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StreamOHLCCandlestickRequest) GetOpenPrice() float64 {
	if x != nil {
		return x.OpenPrice
	}
	return 0
}

func (x *StreamOHLCCandlestickRequest) GetHighPrice() float64 {
	if x != nil {
		return x.HighPrice
	}
	return 0
}

func (x *StreamOHLCCandlestickRequest) GetLowPrice() float64 {
	if x != nil {
		return x.LowPrice
	}
	return 0
}

func (x *StreamOHLCCandlestickRequest) GetClosePrice() float64 {
	if x != nil {
		return x.ClosePrice
	}
	return 0
}

func (x *StreamOHLCCandlestickRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type StreamOHLCCandlestickResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamOHLCCandlestickResponse) Reset() {
	*x = StreamOHLCCandlestickResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_server_protobuf_trading_chart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamOHLCCandlestickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOHLCCandlestickResponse) ProtoMessage() {}

func (x *StreamOHLCCandlestickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_server_protobuf_trading_chart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOHLCCandlestickResponse.ProtoReflect.Descriptor instead.
func (*StreamOHLCCandlestickResponse) Descriptor() ([]byte, []int) {
	return file_grpc_server_protobuf_trading_chart_proto_rawDescGZIP(), []int{1}
}

var File_grpc_server_protobuf_trading_chart_proto protoreflect.FileDescriptor

var file_grpc_server_protobuf_trading_chart_proto_rawDesc = []byte{
	0x0a, 0x28, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x63,
	0x68, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x72, 0x61, 0x64,
	0x69, 0x6e, 0x67, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x74, 0x22, 0xd1, 0x01, 0x0a, 0x1c, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x4f, 0x48, 0x4c, 0x43, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x74,
	0x69, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x69, 0x67, 0x68, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x68, 0x69, 0x67, 0x68, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x6f, 0x77, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x6f, 0x77, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x1f, 0x0a,
	0x1d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4f, 0x48, 0x4c, 0x43, 0x43, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x84,
	0x01, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x61, 0x72, 0x74, 0x12,
	0x74, 0x0a, 0x15, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4f, 0x48, 0x4c, 0x43, 0x43, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x12, 0x2b, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69,
	0x6e, 0x67, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4f,
	0x48, 0x4c, 0x43, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x74, 0x72, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x5f,
	0x63, 0x68, 0x61, 0x72, 0x74, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4f, 0x48, 0x4c, 0x43,
	0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x67, 0x72, 0x70, 0x63, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_server_protobuf_trading_chart_proto_rawDescOnce sync.Once
	file_grpc_server_protobuf_trading_chart_proto_rawDescData = file_grpc_server_protobuf_trading_chart_proto_rawDesc
)

func file_grpc_server_protobuf_trading_chart_proto_rawDescGZIP() []byte {
	file_grpc_server_protobuf_trading_chart_proto_rawDescOnce.Do(func() {
		file_grpc_server_protobuf_trading_chart_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_server_protobuf_trading_chart_proto_rawDescData)
	})
	return file_grpc_server_protobuf_trading_chart_proto_rawDescData
}

var file_grpc_server_protobuf_trading_chart_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_server_protobuf_trading_chart_proto_goTypes = []any{
	(*StreamOHLCCandlestickRequest)(nil),  // 0: trading_chart.StreamOHLCCandlestickRequest
	(*StreamOHLCCandlestickResponse)(nil), // 1: trading_chart.StreamOHLCCandlestickResponse
}
var file_grpc_server_protobuf_trading_chart_proto_depIdxs = []int32{
	0, // 0: trading_chart.TradingChart.StreamOHLCCandlestick:input_type -> trading_chart.StreamOHLCCandlestickRequest
	1, // 1: trading_chart.TradingChart.StreamOHLCCandlestick:output_type -> trading_chart.StreamOHLCCandlestickResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_server_protobuf_trading_chart_proto_init() }
func file_grpc_server_protobuf_trading_chart_proto_init() {
	if File_grpc_server_protobuf_trading_chart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_server_protobuf_trading_chart_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StreamOHLCCandlestickRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_server_protobuf_trading_chart_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StreamOHLCCandlestickResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_server_protobuf_trading_chart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_server_protobuf_trading_chart_proto_goTypes,
		DependencyIndexes: file_grpc_server_protobuf_trading_chart_proto_depIdxs,
		MessageInfos:      file_grpc_server_protobuf_trading_chart_proto_msgTypes,
	}.Build()
	File_grpc_server_protobuf_trading_chart_proto = out.File
	file_grpc_server_protobuf_trading_chart_proto_rawDesc = nil
	file_grpc_server_protobuf_trading_chart_proto_goTypes = nil
	file_grpc_server_protobuf_trading_chart_proto_depIdxs = nil
}
